/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/buildmotion-foundation.module';
import * as i2 from '@angular/common';
import * as i3 from 'buildmotion-alert/buildmotion-alert.module';
import * as i4 from 'buildmotion-logging/buildmotion-logging.module';
export const BuildMotionFoundationModuleNgFactory:i0.NgModuleFactory<i1.BuildMotionFoundationModule> = i0.ɵcmf(i1.BuildMotionFoundationModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i3.BuildMotionAlertModule,i3.BuildMotionAlertModule,
          ([] as any[])),i0.ɵmpd(512,i4.BuildMotionLoggingModule,i4.BuildMotionLoggingModule,
          ([] as any[])),i0.ɵmpd(512,i1.BuildMotionFoundationModule,i1.BuildMotionFoundationModule,
          ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQjovYnVpbGRtb3Rpb24vQnVpbGRNb3Rpb24uQW5ndWxhci9zb3VyY2UvYnVpbGRtb3Rpb24tZm91bmRhdGlvbi9zcmMvYXBwL2J1aWxkbW90aW9uLWZvdW5kYXRpb24ubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0I6L2J1aWxkbW90aW9uL0J1aWxkTW90aW9uLkFuZ3VsYXIvc291cmNlL2J1aWxkbW90aW9uLWZvdW5kYXRpb24vc3JjL2FwcC9idWlsZG1vdGlvbi1mb3VuZGF0aW9uLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
